/**
 * Raw catalog sweep data — one entry per Brick/Stud/Tile/Baseplate candidate
 * found across the globalpayments-samples legacy repos (Copilot Prompt 1
 * output, normalized). component_catalog/generate-catalog.js expands this
 * into catalog.json deterministically.
 *
 * Entry shape (compact):
 *   [idSuffix, layer, name, description, capabilities, depends(idSuffixes),
 *    config, difficulty, files]
 * `files` defaults to per-language glob trees for the repo's languages.
 */
'use strict';

const GP3 = ['GP_APP_ID', 'GP_APP_KEY', 'GP_ENVIRONMENT'];
const PORTICO = ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'PORTICO_ENVIRONMENT'];
const KEYS2 = ['PUBLIC_API_KEY', 'SECRET_API_KEY'];

// repo definitions: { repo, langs, entries: [...] }
const REPOS = [
  {
    repo: 'starter-template',
    langs: ['dotnet', 'go', 'java', 'nodejs', 'php', 'python'],
    entries: [
      ['server-shell', 'baseplate', 'Multi-language server shell',
        'Bootstraps the sample servers, routes, and default exception handling across the template languages.',
        ['http-server bootstrap', 'route registration', 'default error responses', 'static asset serving'],
        [], [], 'medium: shared behavior exists in multiple language-specific entry points rather than one canonical file'],
      ['env-config', 'baseplate', 'Environment configuration loader',
        'Loads SDK credentials and service settings from environment variables for each implementation.',
        ['dotenv loading', 'service URL setup', 'credential binding'],
        ['server-shell'], [...GP3, 'SERVICE_URL'], 'low: the template README and standard file layout make the config pattern explicit'],
      ['hosted-fields-bridge', 'stud', 'Hosted-fields tokenization bridge',
        'Exposes the minimal config and request plumbing needed for a frontend to tokenize payment data and post a token back to the server.',
        ['public config endpoint', 'payment token handoff', 'frontend/backend contract'],
        ['env-config'], GP3, 'medium: tokenization is described at template level but individual endpoint names differ by language'],
      ['payment-placeholder', 'brick', 'Payment processing placeholder',
        'Provides a starter payment endpoint that developers can adapt into charge, authorize, capture, refund, or vault flows.',
        ['sample process-payment endpoint', 'SDK request scaffolding', 'response formatting'],
        ['env-config', 'hosted-fields-bridge'], GP3, 'medium: placeholder logic is intentionally skeletal and spread over all implementations'],
      ['starter-form', 'tile', 'Starter hosted-fields form',
        'Renders the shared sample HTML form used to initialize tokenization and submit a starter payment request.',
        ['payment form', 'hosted fields mount points', 'client-side submit flow'],
        ['hosted-fields-bridge'], [], 'low: implemented in the shared root HTML file', ['starter-template/index.html']],
    ],
  },
  {
    repo: 'online-card-payments',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Application server shell',
        'Bootstraps the language-specific servers and standard JSON error handling for the sale demo.',
        ['HTTP server startup', 'routing', 'JSON success/error responses'],
        [], [], 'medium: implementation is duplicated across four language folders'],
      ['env-config', 'baseplate', 'GP API configuration loader',
        'Loads GP API credentials, environment, and SDK client configuration for sale processing.',
        ['dotenv loading', 'GpApiConfig setup', 'credential binding'],
        ['server-shell'], GP3, 'low: repo README names the required variables and architecture clearly'],
      ['drop-in-access-token', 'stud', 'Drop-In access token generator',
        'Generates the scoped token required to initialize the Drop-In UI before card tokenization.',
        ['scoped token generation', 'frontend bootstrap', 'public endpoint for UI init'],
        ['env-config'], GP3, 'low: the README explicitly documents POST /get-access-token'],
      ['sale-charge', 'brick', 'Sale transaction processor',
        'Submits a tokenized payment reference to the SDK to execute a sale transaction.',
        ['sale/charge', 'billing zip handling', 'transaction response mapping'],
        ['env-config', 'drop-in-access-token'], GP3, 'low: the README explicitly documents POST /process-sale and the sale flow'],
      ['drop-in-ui', 'tile', 'Drop-In payment UI',
        'Renders the shared Drop-In UI experience for card capture and submission.',
        ['drop-in payment form', 'card tokenization UX', 'submit/result states'],
        ['drop-in-access-token'], [], 'low: implemented in the shared root HTML file', ['online-card-payments/index.html']],
    ],
  },
  {
    repo: 'online-check-payments',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Application server shell',
        'Bootstraps the ACH/eCheck servers and shared error handling for direct bank account processing.',
        ['HTTP server startup', 'routing', 'JSON error handling'],
        [], [], 'medium: code lives in four language-specific trees'],
      ['env-config', 'baseplate', 'ACH configuration loader',
        'Loads GP API credentials and service settings used to submit eCheck requests.',
        ['dotenv loading', 'SDK config setup', 'credential binding'],
        ['server-shell'], GP3, 'medium: inferred from sibling repos and topic metadata rather than an opened repo page'],
      ['echeck-charge', 'brick', 'ACH/eCheck payment processor',
        'Builds an eCheck request from raw bank account fields and submits it for payment.',
        ['eCheck/ACH charge', 'routing number use', 'account type handling'],
        ['env-config'], GP3, 'medium: repo behavior is visible from topic metadata but the exact per-language entry files were not expanded'],
      ['ach-form', 'tile', 'ACH payment form',
        'Renders the bank-account form used to collect routing, account, and ownership fields.',
        ['bank account input UI', 'client-side validation', 'form submission'],
        [], [], 'medium: the repo page was not opened directly, so file specifics are inferred from the standard sample layout', ['online-check-payments/index.html']],
    ],
  },
  {
    repo: 'online-recurring-payments',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Recurring payments server shell',
        'Bootstraps the subscription demo servers and standardized response handling.',
        ['server startup', 'route registration', 'JSON responses'],
        [], [], 'medium: repeated across four implementation folders'],
      ['env-config', 'baseplate', 'Recurring billing configuration loader',
        'Loads GP API credentials and SDK client configuration used by initial and recurring charges.',
        ['dotenv loading', 'GpApiConfig setup', 'service selection'],
        ['server-shell'], GP3, 'low: the repository README spells out the shared architecture and language set'],
      ['hosted-fields-access-token', 'stud', 'Hosted-fields access token generator',
        'Publishes the access token used by the frontend to tokenize cards without exposing raw PAN data.',
        ['access token generation', 'frontend bootstrap endpoint', 'tokenization initialization'],
        ['env-config'], GP3, 'low: the README explicitly documents GET /config returning an access token'],
      ['initial-charge', 'brick', 'Initial recurring-setup charge',
        'Processes the first tokenized payment and captures the payment method for future use.',
        ['initial charge', 'customer binding', 'stored credential first use'],
        ['env-config', 'hosted-fields-access-token'], GP3, 'low: the README explains the non-recurring branch of /process-payment in detail'],
      ['stored-credential-recurring-charge', 'brick', 'Stored-credential recurring charge',
        'Submits future recurring charges against the stored payment method without re-entering card data.',
        ['stored credential use', 'scheduled recurring billing', 'vault-backed charging'],
        ['initial-charge'], GP3, 'low: the README explicitly describes the recurring branch of the flow'],
      ['recurring-checkout-form', 'tile', 'Recurring checkout form',
        'Renders the hosted-fields payment form and recurring schedule controls.',
        ['hosted fields', 'schedule selectors', 'recurring options UI'],
        ['hosted-fields-access-token'], [], 'medium: the shared UI exists but schedule widgets are only described in README text', ['online-recurring-payments/index.html']],
    ],
  },
  {
    repo: 'online-payments-auth-and-delayed-capture',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Authorization demo server shell',
        'Bootstraps the auth-only demo servers and standardized error responses.',
        ['server startup', 'routing', 'JSON error handling'],
        [], [], 'medium: there are four separate implementations'],
      ['env-config', 'baseplate', 'Authorization flow configuration loader',
        'Loads payment credentials and SDK config for auth/capture processing.',
        ['dotenv loading', 'SDK config', 'developer identification'],
        ['server-shell'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GP_ENVIRONMENT'], 'low: the repo and PHP README expose the common environment pattern'],
      ['payment-token-bridge', 'stud', 'Payment token handoff',
        'Receives tokenized payment data from the frontend and normalizes it for auth/capture processing.',
        ['token handoff', 'billing zip transport', 'request normalization'],
        ['env-config'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GP_ENVIRONMENT'], 'medium: tokenization is part of the front/back contract but endpoint names vary by implementation'],
      ['authorize', 'brick', 'Authorization processor',
        'Creates an auth-only transaction for a tokenized payment method.',
        ['authorization', 'auth-only request', 'hold funds without capture'],
        ['env-config', 'payment-token-bridge'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GP_ENVIRONMENT'], 'low: authorization is the main documented operation of the repo'],
      ['delayed-capture', 'brick', 'Delayed capture processor',
        'Captures a previously authorized transaction in a second step.',
        ['capture', 'two-step payment flow', 'transaction id reuse'],
        ['authorize'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GP_ENVIRONMENT'], 'medium: capture behavior is repository-level but the exact entry file names differ by language'],
      ['payment-form', 'tile', 'Authorization payment form',
        'Renders the card form used to create tokenized payment data for the auth/capture flow.',
        ['payment form', 'submit auth request', 'status display'],
        ['payment-token-bridge'], [], 'low: the shared root index file implements the form', ['online-payments-auth-and-delayed-capture/index.html']],
    ],
  },
  {
    repo: 'google-pay-payments',
    langs: ['dotnet', 'java', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Google Pay demo server shell',
        'Bootstraps the language-specific Google Pay sample backends and default error handling.',
        ['server startup', 'routing', 'JSON responses'],
        [], [], 'medium: repo metadata shows multiple language trees but the exact entry files were not expanded'],
      ['env-config', 'baseplate', 'Google Pay configuration loader',
        'Loads API credentials and wallet configuration needed to process encrypted Google Pay payloads.',
        ['credential loading', 'wallet config binding', 'SDK/bootstrap config'],
        ['server-shell'], [...GP3, 'GOOGLE_PAY_MERCHANT_ID'], 'medium: inferred from repo description and naming, not a fully opened tree'],
      ['google-pay-token-bridge', 'stud', 'Encrypted wallet payload bridge',
        'Accepts the Google Pay payment payload from the browser and prepares it for server-side processing.',
        ['wallet payload handoff', 'frontend/backend contract', 'token normalization'],
        ['env-config'], [...GP3, 'GOOGLE_PAY_MERCHANT_ID'], 'medium: the repo description confirms token handling, but file-level routes were not inspected'],
      ['google-pay-charge', 'brick', 'Google Pay payment processor',
        'Processes an encrypted Google Pay token through the GP API platform.',
        ['Google Pay charge', 'wallet token processing', 'transaction response mapping'],
        ['env-config', 'google-pay-token-bridge'], [...GP3, 'GOOGLE_PAY_MERCHANT_ID'], 'medium: operation is explicit in repo metadata but not in per-file snippets'],
      ['google-pay-button', 'tile', 'Google Pay button UI',
        'Renders the wallet button and client-side request configuration for Google Pay checkout.',
        ['Google Pay button', 'wallet readiness check', 'checkout initiation'],
        ['google-pay-token-bridge'], [], 'medium: inferred from the sample type and shared repo layout', ['google-pay-payments/index.html']],
    ],
  },
  {
    repo: 'pay-by-link',
    langs: ['dotnet', 'go', 'java', 'nodejs', 'php', 'python'],
    entries: [
      ['server-shell', 'baseplate', 'Pay-by-Link server shell',
        'Bootstraps the payment-link creation API and consistent error responses.',
        ['server startup', 'route registration', 'JSON validation errors'],
        [], [], 'medium: six implementations exist with similar but separate entry points'],
      ['env-config', 'baseplate', 'Payment-link configuration loader',
        'Loads API credentials and environment settings used to create secure payment links.',
        ['dotenv loading', 'credential binding', 'sandbox/production selection'],
        ['server-shell'], GP3, 'low: the README names the shared environment configuration pattern'],
      ['request-validation', 'baseplate', 'Payment-link input validator',
        'Validates amount, currency, and customer fields before link creation.',
        ['input validation', 'sanitization', 'standardized error messages'],
        ['server-shell'], [], 'low: validation is explicitly called out as a core feature of the repo'],
      ['create-payment-link', 'brick', 'Payment-link creator',
        'Creates secure time-limited payment links through the GP API.',
        ['payment link creation', 'multi-currency link payloads', 'remote payment initiation'],
        ['env-config', 'request-validation'], GP3, 'low: the README explicitly documents link creation as the central operation'],
      ['link-generator-ui', 'tile', 'Payment-link generator UI',
        'Renders the form for creating and previewing shareable payment links.',
        ['link generation form', 'amount/currency selectors', 'created-link display'],
        ['create-payment-link'], [], 'low: the shared root HTML file implements the frontend', ['pay-by-link/index.html']],
    ],
  },
  {
    repo: 'php-payments-and-reporting',
    langs: [],
    entries: [
      ['router-shell', 'baseplate', 'PHP router and app shell',
        'Bootstraps the PHP app, routes HTTP requests, and centralizes top-level exception handling.',
        ['router bootstrap', 'request dispatch', 'error handling'],
        [], [], 'low: the repo snippet exposes the router and directory layout directly',
        ['php-payments-and-reporting/router.php', 'php-payments-and-reporting/api/**/*', 'php-payments-and-reporting/src/**/*']],
      ['env-config', 'baseplate', 'PHP SDK configuration loader',
        'Loads GP API credentials and reporting settings from the environment into the PHP SDK layer.',
        ['dotenv loading', 'SDK config binding', 'environment selection'],
        ['router-shell'], GP3, 'medium: config is clear at repo level but actual bootstrapping class names were not expanded',
        ['php-payments-and-reporting/.env.example', 'php-payments-and-reporting/src/**/*', 'php-payments-and-reporting/api/**/*']],
      ['drop-in-access-token', 'stud', 'Drop-In/HPP access token bridge',
        'Provides the client with the token or config needed to initialize the PCI-compliant payment UI.',
        ['frontend init token', 'safe client bootstrap', 'payment reference handoff'],
        ['env-config'], GP3, 'medium: the repo mentions Drop-In/HPP integration, but the exact endpoint files were not opened',
        ['php-payments-and-reporting/api/**/*', 'php-payments-and-reporting/public/**/*']],
      ['verification', 'brick', 'Card verification processor',
        'Runs card verification and auth-style validation checks without performing a sale.',
        ['card verification', 'AVS check', 'CVV check'],
        ['env-config', 'drop-in-access-token'], GP3, 'low: verification is a headline capability of the repository',
        ['php-payments-and-reporting/api/**/*', 'php-payments-and-reporting/src/**/*']],
      ['reporting-query', 'brick', 'Transaction reporting query',
        'Retrieves transaction and verification records for dashboard and reporting views.',
        ['transaction lookup', 'report retrieval', 'report data shaping'],
        ['env-config'], GP3, 'medium: reporting is central to the repo, but the file boundaries are not visible in the snippet',
        ['php-payments-and-reporting/api/**/*', 'php-payments-and-reporting/src/**/*']],
      ['reporting-dashboard', 'tile', 'Verification and reporting dashboard',
        'Renders the UI for running checks and viewing transaction/reporting results.',
        ['dashboard views', 'report tables', 'payment/verification UI'],
        ['drop-in-access-token', 'reporting-query'], [], 'medium: the repo layout shows public assets, but component-level files were not individually enumerated',
        ['php-payments-and-reporting/public/**/*', 'php-payments-and-reporting/docs/**/*']],
    ],
  },
  {
    repo: 'save-and-reuse-payment-methods',
    langs: ['dotnet', 'java', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Saved-methods server shell',
        'Bootstraps the one-click payment sample and standard JSON error handling.',
        ['server startup', 'routing', 'JSON responses'],
        [], [], 'medium: public metadata covers the repo, but the tree itself was not opened'],
      ['env-config', 'baseplate', 'Customer-vault configuration loader',
        'Loads credentials and SDK settings for vault and one-click operations.',
        ['dotenv loading', 'vault config', 'credential binding'],
        ['server-shell'], GP3, 'medium: repo topic metadata exposes capabilities but not individual entry files'],
      ['access-token-bridge', 'stud', 'Frontend tokenization bridge',
        'Publishes the config needed for the frontend to tokenize a card before saving it for reuse.',
        ['frontend bootstrap', 'token handoff', 'client/server contract'],
        ['env-config'], GP3, 'medium: standard sample pattern inferred from neighboring repos'],
      ['vault-create', 'brick', 'Reusable payment method creator',
        'Converts a tokenized payment method into a reusable customer-vault record.',
        ['vault create', 'multi-use token creation', 'payment method storage'],
        ['env-config', 'access-token-bridge'], GP3, 'medium: operation is explicit in repo metadata but file-level details were not expanded'],
      ['one-click-charge', 'brick', 'Saved-method one-click charge',
        'Charges a previously stored payment method without re-entering card data.',
        ['one-click charge', 'stored payment use', 'instant checkout'],
        ['vault-create'], GP3, 'medium: operation is strongly implied by repo description but internal endpoint names were not opened'],
      ['saved-methods-ui', 'tile', 'Saved payment methods UI',
        'Renders the wallet-like checkout for saving and reusing payment methods.',
        ['saved-method list', 'one-click checkout UI', 'card save form'],
        ['access-token-bridge', 'vault-create'], [], 'medium: UI is inferred from the sample theme and common layout', ['save-and-reuse-payment-methods/index.html']],
    ],
  },
  {
    repo: 'embedded-payments-fee-splitting',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Embedded marketplace server shell',
        'Bootstraps the marketplace payment sample and standard API error handling.',
        ['server startup', 'routing', 'error responses'],
        [], [], 'medium: based on topic metadata rather than a fully expanded file tree'],
      ['env-config', 'baseplate', 'Marketplace configuration loader',
        'Loads GP API credentials and fee-splitting settings for embedded marketplace flows.',
        ['dotenv loading', 'merchant credential binding', 'fee config'],
        ['server-shell'], [...GP3, 'PLATFORM_FEE_PERCENT'], 'medium: repository metadata is descriptive, but file-level config code was not inspected'],
      ['embedded-token-bridge', 'stud', 'Embedded payment token bridge',
        'Accepts tokenized customer payment data from the embedded frontend checkout.',
        ['token handoff', 'embedded checkout contract', 'merchant context transport'],
        ['env-config'], GP3, 'medium: inferred from the repo theme and common hosted-fields sample structure'],
      ['marketplace-charge', 'brick', 'Marketplace payment charge',
        'Processes the primary customer payment for the platform transaction.',
        ['charge', 'marketplace payment processing', 'seller context'],
        ['env-config', 'embedded-token-bridge'], GP3, 'medium: capability is explicit in topic metadata but exact endpoint files were not opened'],
      ['fee-split', 'brick', 'Fee-splitting processor',
        'Applies the configured fee split across the platform and sub-merchant parties.',
        ['fee splitting', 'sub-merchant allocation', 'revenue sharing'],
        ['marketplace-charge'], [...GP3, 'PLATFORM_FEE_PERCENT'], 'medium: implementation details are repo-specific and not visible in the search snippet'],
      ['embedded-marketplace-ui', 'tile', 'Embedded marketplace checkout UI',
        'Renders the seller-aware checkout form and fee-splitting payment experience.',
        ['embedded payment form', 'seller selector', 'checkout confirmation'],
        ['embedded-token-bridge'], [], 'medium: shared HTML is assumed, but component-level files were not enumerated', ['embedded-payments-fee-splitting/index.html']],
    ],
  },
  {
    repo: 'localized-checkout-experience',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Localized checkout server shell',
        'Bootstraps the checkout servers and standard response handling across languages.',
        ['server startup', 'route registration', 'error handling'],
        [], [], 'medium: four language trees implement the same behavior separately'],
      ['env-config', 'baseplate', 'Locale-aware payment configuration loader',
        'Loads GP API credentials and language/currency defaults used by the checkout.',
        ['dotenv loading', 'service configuration', 'locale defaults'],
        ['server-shell'], GP3, 'low: the repo README explicitly describes this shared architecture'],
      ['session-preferences', 'stud', 'Session-backed locale preference bridge',
        'Persists selected language and currency preferences between frontend requests and backend payment handling.',
        ['session persistence', 'locale storage', 'currency preference transport'],
        ['env-config'], [], 'low: session persistence is a first-class documented feature of the repo'],
      ['localized-sale', 'brick', 'Localized sale processor',
        'Processes a tokenized sale using the currently selected currency and locale context.',
        ['sale/charge', 'currency-specific processing', 'localized response handling'],
        ['env-config', 'session-preferences'], GP3, 'low: the README ties locale and currency selection directly to payment routing'],
      ['localized-checkout-ui', 'tile', 'Localized checkout UI',
        'Renders the multi-language, multi-currency checkout form and selectors.',
        ['language selector', 'currency selector', 'localized error messages', 'formatted amounts'],
        ['session-preferences'], [], 'low: the shared index file is explicitly part of the sample structure', ['localized-checkout-experience/index.html']],
    ],
  },
  {
    repo: 'donation-form-one-time-recurring-payments',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Donation app server shell',
        'Bootstraps the donation-flow backends with standard JSON error responses.',
        ['server startup', 'route registration', 'error handling'],
        [], [], 'medium: functionality is mirrored across four language folders'],
      ['env-config', 'baseplate', 'Donation flow configuration loader',
        'Loads GP API credentials and recurring-billing defaults for donation processing.',
        ['dotenv loading', 'SDK config', 'recurring setting defaults'],
        ['server-shell'], GP3, 'low: repository README documents the common environment-based configuration'],
      ['drop-in-access-token', 'stud', 'Donation Drop-In access token generator',
        'Supplies the scoped token required to initialize the Drop-In UI for donation checkout.',
        ['frontend token generation', 'Drop-In UI bootstrap', 'safe client initialization'],
        ['env-config'], GP3, 'low: access token generation is explicitly described in the README'],
      ['one-time-donation', 'brick', 'One-time donation processor',
        'Executes a single donation charge from tokenized card data.',
        ['one-time charge', 'donation amount handling', 'transaction response mapping'],
        ['env-config', 'drop-in-access-token'], GP3, 'low: the README names one-time donations as a core capability'],
      ['recurring-donation', 'brick', 'Recurring donation setup',
        'Creates the first recurring donation transaction and stores the credential metadata needed for future billing.',
        ['stored credential setup', 'recurring billing metadata', 'schedule creation'],
        ['env-config', 'drop-in-access-token'], GP3, 'low: recurring donation setup is a first-class feature described in the repo'],
      ['donation-form-ui', 'tile', 'Donation form UI',
        'Renders the unified one-time/recurring donation form and schedule controls.',
        ['drop-in UI mount', 'amount options', 'frequency controls', 'duration controls'],
        ['drop-in-access-token'], [], 'low: the shared root HTML implements the frontend', ['donation-form-one-time-recurring-payments/index.html']],
    ],
  },
  {
    repo: 'basic-refund-tool',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Refund tool server shell',
        'Bootstraps the refund-processing sample and consistent error responses.',
        ['server startup', 'routing', 'JSON errors'],
        [], [], 'medium: repo page itself was not opened, but topic metadata shows a standard multi-language layout'],
      ['env-config', 'baseplate', 'Refund configuration loader',
        'Loads the credentials and environment settings used to perform refund operations.',
        ['dotenv loading', 'SDK config', 'environment selection'],
        ['server-shell'], GP3, 'medium: inferred from the repository description and neighboring sample conventions'],
      ['refund', 'brick', 'Refund processor',
        'Submits a refund request against a prior payment or reference transaction.',
        ['refund', 'transaction id lookup', 'refund response mapping'],
        ['env-config'], GP3, 'low: the repo description identifies refund processing as its primary function'],
      ['refund-form', 'tile', 'Refund request form',
        'Renders the UI for entering transaction and amount details for a refund request.',
        ['refund form', 'transaction reference input', 'status display'],
        ['refund'], [], 'medium: the exact frontend file was not opened but the standard sample layout strongly implies it', ['basic-refund-tool/index.html']],
    ],
  },
  {
    repo: 'reporting-service',
    langs: [],
    entries: [
      ['server-shell', 'baseplate', 'Reporting service server shell',
        'Bootstraps the transaction reporting service and standard API response handling.',
        ['server startup', 'route registration', 'error handling'],
        [], [], 'high: only topic metadata was available, so implementation files are inferred at repo level',
        ['reporting-service/**/*']],
      ['env-config', 'baseplate', 'Reporting-service configuration loader',
        'Loads credentials and report-query defaults used by the reporting service.',
        ['credential loading', 'query defaults', 'environment selection'],
        ['server-shell'], GP3, 'high: repository-level metadata is available, but no file tree was opened',
        ['reporting-service/**/*']],
      ['transaction-search', 'brick', 'Transaction search service',
        'Retrieves transactions using interactive search and filter criteria.',
        ['transaction search', 'filtering', 'report result shaping'],
        ['env-config'], GP3, 'medium: the repo description clearly names search and filtering as core operations',
        ['reporting-service/**/*']],
      ['export-service', 'brick', 'Report export service',
        'Exports report results in CSV, JSON, or XML formats.',
        ['CSV export', 'JSON export', 'XML export'],
        ['transaction-search'], GP3, 'medium: export formats are explicit in repo metadata even though file boundaries are not',
        ['reporting-service/**/*']],
      ['analytics-dashboard', 'tile', 'Reporting dashboard UI',
        'Renders the dashboard, search controls, and export triggers for reporting data.',
        ['dashboard', 'search filters', 'export controls', 'data visualization'],
        ['transaction-search', 'export-service'], [], 'high: only repository metadata was available, so UI files are represented at repo scope',
        ['reporting-service/**/*']],
    ],
  },
  {
    repo: 'integrated-partner-online-payments-with-hosted-fields-api',
    langs: ['dotnet', 'go', 'java', 'nodejs', 'php', 'python'],
    entries: [
      ['server-shell', 'baseplate', 'Partner-payments server shell',
        'Bootstraps the hosted-fields partner-payment backends and standard error responses.',
        ['server startup', 'route registration', 'JSON responses'],
        [], [], 'medium: six implementations follow the same pattern with separate entry files'],
      ['partner-config', 'baseplate', 'Partner credential configuration loader',
        'Loads platform and partner merchant credentials used to sign JWTs and process payments.',
        ['dotenv loading', 'partner account binding', 'credential injection'],
        ['server-shell'], ['AUTHTOKEN_JWT_SECRET', 'ACCOUNT_CREDENTIAL'], 'low: the README explicitly names the JWT secret and account credential requirements'],
      ['partner-jwt', 'stud', 'Hosted-fields JWT generator',
        'Generates the JWT consumed by hosted fields so the frontend can tokenize card data in partner context.',
        ['JWT signing', 'hosted-fields initialization', 'client bootstrap'],
        ['partner-config'], ['AUTHTOKEN_JWT_SECRET', 'ACCOUNT_CREDENTIAL'], 'low: the README explicitly documents this authentication flow'],
      ['partner-charge', 'brick', 'Partner payment processor',
        'Processes the tokenized card payment through the partner-integrated backend flow.',
        ['charge', 'billing data handling', 'partner merchant routing'],
        ['partner-config', 'partner-jwt'], ['AUTHTOKEN_JWT_SECRET', 'ACCOUNT_CREDENTIAL'], 'low: payment processing flow is described directly in the README'],
      ['partner-fee-split', 'brick', 'Partner fee-splitting and merchant injection',
        'Applies partner-specific merchant credential injection and fee-splitting semantics around the core payment call.',
        ['multi-merchant routing', 'fee splitting', 'partner credential injection'],
        ['partner-charge'], ['AUTHTOKEN_JWT_SECRET', 'ACCOUNT_CREDENTIAL'], 'medium: repo description names the pattern, but actual split implementation files were not expanded'],
      ['partner-hosted-fields-ui', 'tile', 'Partner hosted-fields checkout UI',
        'Renders the hosted-fields frontend used for integrated partner payment capture.',
        ['hosted fields UI', 'partner-aware checkout', 'submit/result states'],
        ['partner-jwt'], [], 'low: the shared root HTML file implements the frontend', ['integrated-partner-online-payments-with-hosted-fields-api/index.html']],
    ],
  },
  {
    repo: 'wallet-management',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Wallet-management server shell',
        'Bootstraps the multi-language wallet API and standardized response handling.',
        ['server startup', 'route registration', 'JSON error responses'],
        [], [], 'medium: multiple language implementations carry the same behavior'],
      ['env-config', 'baseplate', 'Wallet configuration loader',
        'Loads credentials and storage settings used to create and manage multi-use tokens.',
        ['dotenv loading', 'credential binding', 'storage path config'],
        ['server-shell'], GP3, 'low: the README explains the configuration and mock-mode system at repo level'],
      ['access-token-bridge', 'stud', 'Wallet tokenization bridge',
        'Provides the frontend config needed to tokenize a card before converting it into a multi-use token.',
        ['public config endpoint', 'token handoff', 'client bootstrap'],
        ['env-config'], GP3, 'medium: token creation is explicit but not every route name was visible'],
      ['multi-use-token-create', 'brick', 'Multi-use token creator',
        'Converts a single-use token into a reusable stored payment method token.',
        ['multi-use token creation', 'stored payment tokenization', 'customer data association'],
        ['env-config', 'access-token-bridge'], GP3, 'low: repo README explicitly calls out multi-use token creation'],
      ['payment-method-crud', 'brick', 'Payment method CRUD',
        'Lists and updates stored payment method metadata, including nickname and default selection.',
        ['list stored methods', 'edit nickname', 'default payment method flag'],
        ['multi-use-token-create'], GP3, 'low: CRUD endpoints are enumerated directly in the README'],
      ['wallet-ui', 'tile', 'Wallet management UI',
        'Renders the UI for listing, editing, and adding payment methods.',
        ['saved-method list', 'edit controls', 'add payment method form'],
        ['access-token-bridge', 'payment-method-crud'], [], 'low: the shared interface is part of the documented sample flow', ['wallet-management/index.html']],
    ],
  },
  {
    repo: 'network-tokenization',
    langs: ['dotnet', 'go', 'java', 'nodejs', 'php', 'python'],
    entries: [
      ['server-shell', 'baseplate', 'Network-tokenization server shell',
        'Bootstraps the sample servers and standardized error responses for network token flows.',
        ['server startup', 'route registration', 'JSON errors'],
        [], [], 'medium: repository metadata exists, but the tree itself was not expanded'],
      ['env-config', 'baseplate', 'Network-token configuration loader',
        'Loads credentials and settings required for network token provisioning and use.',
        ['credential loading', 'wallet/token config', 'environment selection'],
        ['server-shell'], GP3, 'medium: inferred from repo description and sample conventions'],
      ['drop-in-token-bridge', 'stud', 'Tokenization bridge for network-token flows',
        'Connects the frontend tokenization experience to backend provisioning of network tokens.',
        ['token handoff', 'frontend bootstrap', 'payment reference transport'],
        ['env-config'], GP3, 'medium: topic metadata identifies drop-in UI usage, but route files were not opened'],
      ['network-token-provision', 'brick', 'Network token provisioning',
        'Replaces card numbers with issuer network tokens for secure storage and later use.',
        ['network token provisioning', 'secure storage token', 'card replacement'],
        ['env-config', 'drop-in-token-bridge'], GP3, 'low: the repo topic description explicitly defines this operation'],
      ['network-token-charge', 'brick', 'Network-token payment processor',
        'Uses the resulting network token in a subsequent payment operation.',
        ['charge with network token', 'stored token usage', 'transaction processing'],
        ['network-token-provision'], GP3, 'medium: charging is implied by the sample theme but less explicit than provisioning in metadata'],
      ['network-token-ui', 'tile', 'Network tokenization UI',
        'Renders the sample form and status views for provisioning and using network tokens.',
        ['tokenization form', 'provision request UI', 'result display'],
        ['drop-in-token-bridge'], [], 'medium: UI is implied by the standard sample structure, not individually opened', ['network-tokenization/index.html']],
    ],
  },
  {
    repo: 'gpecom-3ds2',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', '3DS2 backend shell',
        'Bootstraps the language-specific 3DS2 servers and response handling for each step of the EMV 3DS flow.',
        ['server startup', 'route registration', 'JSON/http callback handling'],
        [], [], 'medium: the repo page describes the structure, but internal handler file names are mixed across languages'],
      ['env-config', 'baseplate', '3DS2 configuration loader',
        'Loads gateway credentials and service settings used for 3DS2 enrollment, auth, and payment.',
        ['credential loading', 'gateway config', 'sandbox endpoint setup'],
        ['server-shell'], ['MERCHANT_ID', 'ACCOUNT_ID', 'SHARED_SECRET', 'SERVICE_URL'], 'low: credentials and API type are clear from the README summary'],
      ['method-and-challenge-webhooks', 'stud', 'Method URL and challenge callback receivers',
        'Receives raw 3DS2 method and challenge notifications from the browser/ACS during authentication.',
        ['method notification endpoint', 'challenge notification endpoint', 'raw callback intake'],
        ['env-config'], [], 'low: the README explicitly lists webhook handlers in the PHP implementation and equivalent single-file servers elsewhere',
        ['gpecom-3ds2/php/webhooks/**/*', 'gpecom-3ds2/nodejs/**/*', 'gpecom-3ds2/dotnet/**/*', 'gpecom-3ds2/java/**/*']],
      ['enrollment-check', 'brick', '3DS2 enrollment check',
        'Checks protocol versions and card enrollment before continuing the flow.',
        ['protocol version check', 'card enrollment lookup', 'pre-auth decisioning'],
        ['env-config'], ['MERCHANT_ID', 'ACCOUNT_ID', 'SHARED_SECRET', 'SERVICE_URL'], 'low: the README explicitly maps enrollment to POST /3ds2/protocol-versions',
        ['gpecom-3ds2/php/api/**/*', 'gpecom-3ds2/nodejs/**/*', 'gpecom-3ds2/dotnet/**/*', 'gpecom-3ds2/java/**/*']],
      ['authentication', 'brick', '3DS2 authentication and challenge initiation',
        'Initiates authentication and challenge handling with device fingerprinting and issuer redirects as needed.',
        ['authenticate', 'device fingerprinting', 'challenge initiation'],
        ['enrollment-check', 'method-and-challenge-webhooks'], ['MERCHANT_ID', 'ACCOUNT_ID', 'SHARED_SECRET', 'SERVICE_URL'], 'low: the README explicitly documents authentication, method URL, and challenge steps',
        ['gpecom-3ds2/php/api/**/*', 'gpecom-3ds2/nodejs/**/*', 'gpecom-3ds2/dotnet/**/*', 'gpecom-3ds2/java/**/*']],
      ['post-auth-payment', 'brick', 'Post-auth payment authorization',
        'Submits the final payment authorization using the authenticated 3DS2 data.',
        ['payment authorization', '3DS2 data attachment', 'XML/SDK payment call'],
        ['authentication'], ['MERCHANT_ID', 'ACCOUNT_ID', 'SHARED_SECRET', 'SERVICE_URL'], 'low: the README explicitly describes payment as the final step and points to core implementation files',
        ['gpecom-3ds2/php/src/GpecomClient.php', 'gpecom-3ds2/nodejs/server.js', 'gpecom-3ds2/dotnet/Program.cs', 'gpecom-3ds2/java/src/**/*']],
      ['three-ds-test-ui', 'tile', '3DS2 test harness UI',
        'Renders the shared frontend for enrollment, challenge, card selection, and backend switching.',
        ['3DS2 form', 'test card selector', 'backend selector', 'ACS iframe host'],
        ['enrollment-check', 'authentication'], [], 'low: the README explicitly states the shared frontend lives in index.html',
        ['gpecom-3ds2/index.html']],
    ],
  },
  {
    repo: 'portico-online-card-payments',
    langs: ['dotnet', 'go', 'java', 'nodejs', 'php', 'python'],
    entries: [
      ['server-shell', 'baseplate', 'Portico card server shell',
        'Bootstraps the Portico card-payment backends and default JSON error handling.',
        ['server startup', 'route registration', 'JSON responses'],
        [], [], 'medium: six implementations follow the same pattern'],
      ['env-config', 'baseplate', 'Portico card configuration loader',
        'Loads Portico credentials and SDK configuration for tokenized card sales.',
        ['dotenv loading', 'Portico config setup', 'developer identification'],
        ['server-shell'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'DEVELOPER_ID', 'VERSION_NUMBER'], 'low: the README states environment-based configuration with public/private API keys'],
      ['public-config-endpoint', 'stud', 'Public API key/config bridge',
        'Exposes the public configuration needed for client-side Portico tokenization.',
        ['GET /config-style endpoint', 'public API key delivery', 'frontend bootstrap'],
        ['env-config'], KEYS2, 'low: the README explicitly documents GET /config and public/private API key management'],
      ['sale-charge', 'brick', 'Portico card sale processor',
        'Processes a tokenized card payment through the Portico gateway.',
        ['sale/charge', 'billing zip handling', 'Portico transaction response'],
        ['env-config', 'public-config-endpoint'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'DEVELOPER_ID', 'VERSION_NUMBER'], 'low: the README clearly defines POST /process-payment and the demo charge flow'],
      ['hosted-fields-form', 'tile', 'Portico hosted-fields form',
        'Renders the shared test form used for Portico tokenization and payment submission.',
        ['payment form', 'hosted fields', 'submit/result states'],
        ['public-config-endpoint'], [], 'low: the shared root HTML file is explicitly present in the repo', ['portico-online-card-payments/index.html']],
    ],
  },
  {
    repo: 'portico-online-check-payments',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Portico ACH server shell',
        'Bootstraps the Portico ACH/eCheck sample backends and standard responses.',
        ['server startup', 'route registration', 'JSON error handling'],
        [], [], 'medium: code is distributed across four language implementations'],
      ['env-config', 'baseplate', 'Portico ACH configuration loader',
        'Loads Portico credentials and gateway settings for eCheck processing.',
        ['dotenv loading', 'PorticoConfig setup', 'environment binding'],
        ['server-shell'], PORTICO, 'low: the README explicitly states this repo uses PorticoConfig'],
      ['echeck-charge', 'brick', 'Portico eCheck processor',
        'Constructs an ECheck object from raw bank account inputs and submits it to Portico.',
        ['eCheck payment', 'bank routing/account processing', 'server-side ACH flow'],
        ['env-config'], PORTICO, 'low: the README explicitly details that ACH processing is entirely server-side'],
      ['ach-form', 'tile', 'Portico ACH form',
        'Renders the frontend bank-account form used to post ACH/eCheck requests.',
        ['bank account form', 'routing/account fields', 'submission UI'],
        ['echeck-charge'], [], 'low: the shared root HTML file is listed in the repo page', ['portico-online-check-payments/index.html']],
    ],
  },
  {
    repo: 'portico-online-recurring-payments',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Portico recurring server shell',
        'Bootstraps recurring-billing backends for the Portico gateway.',
        ['server startup', 'routing', 'error handling'],
        [], [], 'medium: public metadata confirms the repo but the tree was not expanded'],
      ['env-config', 'baseplate', 'Portico recurring configuration loader',
        'Loads gateway credentials and recurring-billing settings for Portico flows.',
        ['dotenv loading', 'gateway config', 'customer-vault settings'],
        ['server-shell'], PORTICO, 'medium: inferred from repo description and family of similar Portico samples'],
      ['tokenization-bridge', 'stud', 'Recurring tokenization bridge',
        'Supplies frontend configuration so the first recurring payment can be tokenized safely.',
        ['frontend bootstrap', 'token handoff', 'payment method capture'],
        ['env-config'], KEYS2, 'medium: repo metadata suggests standard hosted-fields behavior, but routes were not inspected'],
      ['initial-recurring-charge', 'brick', 'Initial Portico recurring charge',
        'Processes the initial transaction and stores the payment method/customer context.',
        ['initial charge', 'payment method storage', 'customer management'],
        ['env-config', 'tokenization-bridge'], PORTICO, 'medium: capability is explicit in repo description but file-level details were not visible'],
      ['scheduled-recurring-charge', 'brick', 'Scheduled Portico recurring charge',
        'Uses the stored payment method to execute future recurring transactions.',
        ['recurring billing', 'stored payment usage', 'customer-vault charge'],
        ['initial-recurring-charge'], PORTICO, 'medium: operation is explicit in repo metadata but implementation files were not opened'],
      ['recurring-ui', 'tile', 'Portico recurring checkout UI',
        'Renders the UI for initial enrollment and recurring schedule selection.',
        ['checkout form', 'recurring controls', 'status display'],
        ['tokenization-bridge'], [], 'medium: UI structure inferred from sample category and standard repo layout', ['portico-online-recurring-payments/index.html']],
    ],
  },
  {
    repo: 'portico-save-and-reuse-payment-methods',
    langs: ['dotnet', 'go', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Portico saved-methods server shell',
        'Bootstraps the Portico one-click payment sample and standard responses.',
        ['server startup', 'route registration', 'error handling'],
        [], [], 'medium: topic metadata confirms five language implementations but not per-file details'],
      ['env-config', 'baseplate', 'Portico vault configuration loader',
        'Loads Portico credentials and token-management settings used for saved methods.',
        ['dotenv loading', 'customer-vault config', 'credential binding'],
        ['server-shell'], PORTICO, 'medium: inferred from repo metadata rather than an opened page'],
      ['tokenization-bridge', 'stud', 'Portico tokenization bridge',
        'Provides the public config needed to tokenize and submit a card for saving.',
        ['public config endpoint', 'token handoff', 'client bootstrap'],
        ['env-config'], KEYS2, 'medium: standard sample pattern is inferred from related Portico repos'],
      ['vault-create', 'brick', 'Portico reusable payment method creator',
        'Stores a tokenized payment method as a multi-use Portico vault/customer record.',
        ['vault create', 'multi-use token storage', 'customer-vault binding'],
        ['env-config', 'tokenization-bridge'], PORTICO, 'medium: capability is explicit in topic metadata but file-level routes were not opened'],
      ['one-click-charge', 'brick', 'Portico one-click charge',
        'Uses a stored Portico payment method to complete checkout immediately.',
        ['one-click charge', 'stored payment use', 'streamlined checkout'],
        ['vault-create'], PORTICO, 'medium: functionality is stated in the repo description but not expanded into files'],
      ['saved-methods-ui', 'tile', 'Portico saved-methods checkout UI',
        'Renders the checkout for saving and reusing Portico payment methods.',
        ['saved-method selector', 'save-card form', 'one-click checkout UI'],
        ['tokenization-bridge', 'vault-create'], [], 'medium: UI is inferred from the sample theme and standard repo layout', ['portico-save-and-reuse-payment-methods/index.html']],
    ],
  },
  {
    repo: 'portico-google-pay-payments',
    langs: [],
    entries: [
      ['server-shell', 'baseplate', 'Portico Google Pay server shell',
        'Bootstraps the Portico Google Pay sample backends and standardized responses.',
        ['server startup', 'routing', 'JSON error handling'],
        [], [], 'high: only topic metadata was available, so file paths are represented at repo scope',
        ['portico-google-pay-payments/**/*']],
      ['env-config', 'baseplate', 'Portico Google Pay configuration loader',
        'Loads Portico credentials and Google Pay settings for wallet payments.',
        ['credential loading', 'wallet config', 'environment selection'],
        ['server-shell'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GOOGLE_PAY_MERCHANT_ID'], 'high: repo-level metadata exists but the file tree was not opened',
        ['portico-google-pay-payments/**/*']],
      ['google-pay-token-bridge', 'stud', 'Portico wallet payload bridge',
        'Accepts Google Pay payment data and prepares it for Portico processing.',
        ['wallet payload handoff', 'frontend/backend contract', 'token normalization'],
        ['env-config'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GOOGLE_PAY_MERCHANT_ID'], 'medium: repo metadata clearly mentions Google Pay token processing',
        ['portico-google-pay-payments/**/*']],
      ['google-pay-charge', 'brick', 'Portico Google Pay processor',
        'Processes the Google Pay token using the Portico gateway flow.',
        ['Google Pay charge', 'wallet token processing', 'Portico payment response'],
        ['env-config', 'google-pay-token-bridge'], ['PUBLIC_API_KEY', 'SECRET_API_KEY', 'GOOGLE_PAY_MERCHANT_ID'], 'medium: operation is explicit in repo description even though file boundaries are not visible',
        ['portico-google-pay-payments/**/*']],
      ['google-pay-button', 'tile', 'Portico Google Pay button UI',
        'Renders the wallet button and client-side request construction for Google Pay.',
        ['Google Pay button', 'wallet initialization', 'checkout initiation'],
        ['google-pay-token-bridge'], [], 'high: the repo tree was not opened, so UI files are represented at repo scope',
        ['portico-google-pay-payments/**/*']],
    ],
  },
  {
    repo: 'portico-embedded-payments-fee-splitting',
    langs: ['dotnet', 'java', 'nodejs', 'php'],
    entries: [
      ['server-shell', 'baseplate', 'Portico marketplace server shell',
        'Bootstraps the embedded Portico marketplace sample and standard responses.',
        ['server startup', 'routing', 'JSON error handling'],
        [], [], 'medium: four implementation trees share one architecture'],
      ['config-loader', 'baseplate', 'Portico and ProPay configuration loader',
        'Loads the Portico payment credentials and optional ProPay SplitFunds credentials.',
        ['dotenv loading', 'dual credential binding', 'mock split-funds fallback'],
        ['server-shell'],
        ['PORTICO_PUBLIC_API_KEY', 'PORTICO_SECRET_API_KEY', 'PORTICO_DEVELOPER_ID', 'PORTICO_VERSION_NUMBER', 'PORTICO_ENVIRONMENT', 'PROPAY_USERNAME', 'PROPAY_PASSWORD', 'PROPAY_CERT_STR', 'PROPAY_TERM_ID'],
        'low: the repo README lists the credential groups and fallback behavior explicitly'],
      ['hosted-fields-bridge', 'stud', 'Hosted-fields tokenization bridge',
        'Publishes the client-side config needed to tokenize the card in the embedded marketplace checkout.',
        ['public tokenization config', 'frontend bootstrap', 'token handoff'],
        ['config-loader'],
        ['PORTICO_PUBLIC_API_KEY', 'PORTICO_SECRET_API_KEY', 'PORTICO_DEVELOPER_ID', 'PORTICO_VERSION_NUMBER', 'PORTICO_ENVIRONMENT'],
        'medium: hosted-fields usage is explicit, but route files were not enumerated'],
      ['portico-charge', 'brick', 'Primary Portico customer charge',
        'Processes the shopper payment through the Portico gateway before payout distribution.',
        ['charge', 'platform payment collection', 'seller validation'],
        ['config-loader', 'hosted-fields-bridge'],
        ['PORTICO_PUBLIC_API_KEY', 'PORTICO_SECRET_API_KEY', 'PORTICO_DEVELOPER_ID', 'PORTICO_VERSION_NUMBER', 'PORTICO_ENVIRONMENT'],
        'low: the architecture overview explicitly lists backend charging as a core step'],
      ['split-funds', 'brick', 'ProPay SplitFunds payout',
        'Transfers the seller payout after the platform fee is calculated.',
        ['SplitFunds payout', 'platform fee calculation', 'seller disbursement'],
        ['portico-charge'],
        ['PORTICO_PUBLIC_API_KEY', 'PORTICO_SECRET_API_KEY', 'PORTICO_DEVELOPER_ID', 'PORTICO_VERSION_NUMBER', 'PORTICO_ENVIRONMENT', 'PROPAY_USERNAME', 'PROPAY_PASSWORD', 'PROPAY_CERT_STR', 'PROPAY_TERM_ID'],
        'low: the README explicitly describes SplitFunds and its mock fallback'],
      ['marketplace-ui', 'tile', 'Marketplace payment and seller UI',
        'Renders the embedded checkout form, seller selector, and fee breakdown display.',
        ['hosted fields UI', 'seller selection', 'fee breakdown'],
        ['hosted-fields-bridge'], [], 'medium: UI capabilities are described, though the root file list snippet did not show index.html explicitly',
        ['portico-embedded-payments-fee-splitting/index.html']],
    ],
  },
  {
    repo: 'portico-donation-form-one-time-recurring-payments',
    langs: ['dotnet', 'java', 'nodejs'],
    entries: [
      ['server-shell', 'baseplate', 'Portico donation server shell',
        'Bootstraps the Portico donation sample and request routing for one-time and recurring flows.',
        ['server startup', 'routing', 'error handling'],
        [], [], 'medium: repo tree details are clearest in PHP, with other languages inferred from the repo family',
        ['portico-donation-form-one-time-recurring-payments/dotnet/**/*', 'portico-donation-form-one-time-recurring-payments/java/**/*', 'portico-donation-form-one-time-recurring-payments/nodejs/**/*', 'portico-donation-form-one-time-recurring-payments/php/**/*']],
      ['config-loader', 'baseplate', 'Portico donation configuration loader',
        'Loads Portico credentials for donation processing and public API key delivery.',
        ['dotenv loading', 'public API key config', 'gateway setup'],
        ['server-shell'], KEYS2, 'low: the PHP tree explicitly shows config.php and the public/secret key env variables',
        ['portico-donation-form-one-time-recurring-payments/php/config.php', 'portico-donation-form-one-time-recurring-payments/dotnet/**/*', 'portico-donation-form-one-time-recurring-payments/java/**/*', 'portico-donation-form-one-time-recurring-payments/nodejs/**/*']],
      ['public-config-endpoint', 'stud', 'Donation public-config endpoint',
        'Returns the public API key/config used by hosted fields for the donation form.',
        ['GET /config style endpoint', 'public API key delivery', 'frontend bootstrap'],
        ['config-loader'], KEYS2, 'low: the PHP README excerpt explicitly identifies config.php as GET /config',
        ['portico-donation-form-one-time-recurring-payments/php/config.php', 'portico-donation-form-one-time-recurring-payments/dotnet/**/*', 'portico-donation-form-one-time-recurring-payments/java/**/*', 'portico-donation-form-one-time-recurring-payments/nodejs/**/*']],
      ['donation-router', 'stud', 'Donation request router',
        'Routes submitted donations into one-time or recurring processing paths.',
        ['payment_type routing', 'request normalization', 'flow dispatch'],
        ['config-loader'], KEYS2, 'low: the PHP tree explicitly exposes process-donation.php and its routing role',
        ['portico-donation-form-one-time-recurring-payments/php/process-donation.php', 'portico-donation-form-one-time-recurring-payments/dotnet/**/*', 'portico-donation-form-one-time-recurring-payments/java/**/*', 'portico-donation-form-one-time-recurring-payments/nodejs/**/*']],
      ['one-time-donation', 'brick', 'Portico one-time donation processor',
        'Executes a single donation charge through Portico.',
        ['one-time charge', 'donation amount handling', 'transaction response mapping'],
        ['donation-router'], KEYS2, 'low: the PHP tree explicitly exposes process-one-time.php',
        ['portico-donation-form-one-time-recurring-payments/php/process-one-time.php', 'portico-donation-form-one-time-recurring-payments/dotnet/**/*', 'portico-donation-form-one-time-recurring-payments/java/**/*', 'portico-donation-form-one-time-recurring-payments/nodejs/**/*']],
      ['recurring-donation', 'brick', 'Portico recurring donation processor',
        'Creates the customer, payment method, and billing schedule required for recurring donations.',
        ['customer create', 'payment method create', 'schedule create', 'recurring billing'],
        ['donation-router'], KEYS2, 'low: the PHP README excerpt explicitly states the Customer → PaymentMethod → Schedule chain',
        ['portico-donation-form-one-time-recurring-payments/php/process-recurring.php', 'portico-donation-form-one-time-recurring-payments/dotnet/**/*', 'portico-donation-form-one-time-recurring-payments/java/**/*', 'portico-donation-form-one-time-recurring-payments/nodejs/**/*']],
      ['donation-form-ui', 'tile', 'Portico donation form UI',
        'Renders the hosted-fields donation form with one-time and recurring donation options.',
        ['donation form', 'frequency selectors', 'amount widgets', 'submit/result states'],
        ['public-config-endpoint'], [], 'low: the PHP tree explicitly includes index.html for the donation form',
        ['portico-donation-form-one-time-recurring-payments/php/index.html', 'portico-donation-form-one-time-recurring-payments/index.html']],
    ],
  },
];

module.exports = { REPOS };
